"""add product stock

Revision ID: bb1203ab14b1
Revises: 1012f13bcd2d
Create Date: 2026-03-19 12:04:20.080971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1203ab14b1'
down_revision: Union[str, Sequence[str], None] = '1012f13bcd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product_category', 'store_info', ['store_id'], ['id'])
    op.add_column('product_list', sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
    op.add_column('product_list', sa.Column('is_active', sa.Boolean(),server_default='true', nullable=False))
    op.add_column('product_list', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    op.alter_column('product_list', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('product_list_barcode_key'), 'product_list', type_='unique')
    op.create_foreign_key(None, 'product_list', 'shelve_info', ['shelve_id'], ['id'])
    op.create_foreign_key(None, 'product_list', 'store_info', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_list', type_='foreignkey')
    op.drop_constraint(None, 'product_list', type_='foreignkey')
    op.create_unique_constraint(op.f('product_list_barcode_key'), 'product_list', ['barcode'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_list', 'image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('product_list', 'expiration_date')
    op.drop_column('product_list', 'is_active')
    op.drop_column('product_list', 'stock')
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    # ### end Alembic commands ###
