"""add_stock_managed_and_refund_fields

Revision ID: 9e0b876da210
Revises: 55572a60d181
Create Date: 2026-06-08 22:48:10.714564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0b876da210'
down_revision: Union[str, Sequence[str], None] = '55572a60d181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_info', sa.Column('refund_amount', sa.Integer(), nullable=True))
    op.add_column('order_info', sa.Column('refund_reason', sa.String(), nullable=True))
    op.add_column('order_info', sa.Column('refund_method', sa.String(), nullable=True))
    op.add_column('order_info', sa.Column('refunded_at', sa.DateTime(), nullable=True))
    op.add_column('product_list', sa.Column('stock_managed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_list', 'stock_managed')
    op.drop_column('order_info', 'refunded_at')
    op.drop_column('order_info', 'refund_method')
    op.drop_column('order_info', 'refund_reason')
    op.drop_column('order_info', 'refund_amount')
    # ### end Alembic commands ###
